#!/usr/bin/env bash
# ============================================================================
# BL4CK RMM — fresh-VPS installer (TEST / pre-signing)
# ============================================================================
# Stands up the full stack on a fresh Ubuntu amd64 VPS:
#   - builds the API / web / portal images FROM SOURCE (no release needed)
#   - BINARY_SOURCE=local — serves UNSIGNED Windows installers you stage on disk
#   - Caddy automatic Let's Encrypt HTTPS for your domain
#   - Postgres + Redis in containers; migrations + admin seed run on first boot
#
# This is the "test it now, sign later" path. When your code-signing cert lands,
# flip BINARY_SOURCE=github with a signed release — no re-architecture.
#
# Usage (run from the repo root, as a user in the `docker` group or via sudo):
#   ./deploy/install.sh --domain rmm.example.com --admin-email you@example.com
#
# Prerequisites:
#   - The domain's A record already points at this VPS's public IP.
#   - Ports 80 and 443 open (Let's Encrypt + HTTPS).
#   - docker + docker compose plugin + git + openssl installed.
# After it finishes, stage your Windows installers with:
#   ./deploy/stage-binaries.sh /path/to/dir/with/bl4ck-*.exe-and-.msi
# ============================================================================
set -euo pipefail

DOMAIN=""
ADMIN_EMAIL=""
ACME_EMAIL=""
BINARIES_RELEASE=""
BINARIES_REPO="bl4ckxr0sexd/bl4ck"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)           DOMAIN="$2"; shift 2 ;;
    --admin-email)      ADMIN_EMAIL="$2"; shift 2 ;;
    --acme-email)       ACME_EMAIL="$2"; shift 2 ;;
    --binaries-release) BINARIES_RELEASE="$2"; shift 2 ;;
    --binaries-repo)    BINARIES_REPO="$2"; shift 2 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

fail() { echo "ERROR: $*" >&2; exit 1; }

[[ -n "$DOMAIN" ]]      || fail "--domain is required (e.g. --domain rmm.example.com)"
[[ -n "$ADMIN_EMAIL" ]] || fail "--admin-email is required (the first dashboard admin login)"
ACME_EMAIL="${ACME_EMAIL:-$ADMIN_EMAIL}"

# Repo root = parent of this script's dir.
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

# Stable, predictable project name so the binaries volume is `bl4ck_binaries`
# (stage-binaries.sh relies on this).
export COMPOSE_PROJECT_NAME=bl4ck
COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.override.yml.local-build)

# ----- prerequisites -----
command -v docker  >/dev/null 2>&1 || fail "docker not found. Install: https://docs.docker.com/engine/install/ubuntu/"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not found (install docker-compose-plugin)"
command -v openssl >/dev/null 2>&1 || fail "openssl not found (apt-get install -y openssl)"
docker info >/dev/null 2>&1 || fail "cannot talk to the Docker daemon — is it running, and are you in the 'docker' group (or using sudo)?"

rand() { openssl rand -hex 32; }

# ----- .env (generated once; never overwritten) -----
if [[ -f .env ]]; then
  echo "==> .env already exists — keeping it (delete it to regenerate)."
else
  echo "==> Generating .env with fresh secrets..."
  ADMIN_PW="$(openssl rand -base64 24)"
  umask 077
  cat > .env <<EOF
# BL4CK RMM — generated by deploy/install.sh (local-mode test deploy).
# SECRET FILE. The encryption keys below are UNRECOVERABLE — back this up.

# ---- Identity / TLS ----
BREEZE_DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
CORS_ALLOWED_ORIGINS=https://${DOMAIN}
IS_HOSTED=false
ENABLE_REGISTRATION=false

# ---- Build from source on amd64 ----
DOCKER_PLATFORM=linux/amd64
BREEZE_VERSION=0.0.0-local
BREEZE_API_IMAGE_REF=breeze-api:local
BREEZE_WEB_IMAGE_REF=breeze-web:local
BREEZE_PORTAL_IMAGE_REF=breeze-portal:local
BREEZE_BINARIES_IMAGE_REF=alpine:3.19
POSTGRES_IMAGE_REF=postgres:16-alpine
REDIS_IMAGE_REF=redis:7-alpine
CADDY_IMAGE_REF=caddy:2-alpine

# ---- Installer delivery: local disk (unsigned installers you stage) ----
BINARY_SOURCE=local
# Public release trust anchor. REQUIRED to boot in production even for local
# mode. This is the public key shipped in deploy/.env.example — safe to keep
# as-is for testing (only matters for verifying official signed releases).
RELEASE_ARTIFACT_MANIFEST_PUBLIC_KEYS=yzx8ftmcls6uBetFC5SYnZhBo+cbur3IX50TbBthTso=

# ---- Database (containerized Postgres) ----
POSTGRES_USER=bl4ck
POSTGRES_DB=bl4ck
POSTGRES_PASSWORD=$(rand)
BREEZE_APP_DB_PASSWORD=$(rand)

# ---- Redis ----
REDIS_PASSWORD=$(rand)

# ---- Secrets (all mutually distinct — required in production) ----
JWT_SECRET=$(rand)
AGENT_ENROLLMENT_SECRET=$(rand)
APP_ENCRYPTION_KEY=$(rand)
MFA_ENCRYPTION_KEY=$(rand)
ENROLLMENT_KEY_PEPPER=$(rand)
MFA_RECOVERY_CODE_PEPPER=$(rand)

# ---- Reverse-proxy trust ----
# Caddy fronts the API on a single box. false = don't trust X-Forwarded-For
# (avoids pinning Caddy's dynamic container IP). Client-IP features (partner IP
# allowlist) won't see real IPs, but core enrollment/dashboard work fine.
TRUST_PROXY_HEADERS=false

# ---- First admin (seeded on empty DB; setup wizard on first login) ----
BREEZE_BOOTSTRAP_ADMIN_EMAIL=${ADMIN_EMAIL}
BREEZE_BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PW}
BREEZE_BOOTSTRAP_ADMIN_NAME=Admin

# ---- Email (invites disabled for the test; fill in later if needed) ----
EMAIL_PROVIDER=auto
EMAIL_FROM=noreply@${DOMAIN}
EOF
  chmod 600 .env
  printf '%s\n' "$ADMIN_PW" > .admin-password.txt
  chmod 600 .admin-password.txt
  echo "    Admin password written to $(pwd)/.admin-password.txt (chmod 600)."
fi

# ----- bring the stack up (build from source) -----
echo "==> Building images from source and starting the stack (first build ~5-10 min)..."
"${COMPOSE[@]}" up --build -d

# ----- wait for API health -----
echo "==> Waiting for the API to become healthy (migrations + admin seed run now)..."
healthy=0
for _ in $(seq 1 60); do
  if "${COMPOSE[@]}" exec -T api wget -qO- http://127.0.0.1:3001/health 2>/dev/null | grep -q '"status":"ok"'; then
    healthy=1; break
  fi
  sleep 5
done
if [[ "$healthy" -ne 1 ]]; then
  echo "WARNING: API did not report healthy within ~5 min. Check logs:" >&2
  echo "  ${COMPOSE[*]} logs api | tail -n 100" >&2
else
  echo "    API is healthy."
fi

# ----- auto-stage installers from a GitHub release (if requested) -----
if [[ -n "$BINARIES_RELEASE" ]]; then
  echo "==> Staging installers from GitHub release '${BINARIES_RELEASE}' (${BINARIES_REPO})..."
  ./deploy/stage-binaries.sh --release "$BINARIES_RELEASE" --repo "$BINARIES_REPO" || \
    echo "WARNING: installer staging failed — run ./deploy/stage-binaries.sh manually." >&2
fi

echo ""
echo "============================================================================"
echo "  BL4CK is up (build-from-source, local installer mode)."
echo "----------------------------------------------------------------------------"
echo "  Dashboard : https://${DOMAIN}"
echo "  Admin     : ${ADMIN_EMAIL}"
if [[ -f .admin-password.txt ]]; then
  echo "  Password  : $(cat .admin-password.txt)   (also in .admin-password.txt)"
fi
echo ""
echo "  Caddy issues the Let's Encrypt cert on first HTTPS hit once DNS for"
echo "  ${DOMAIN} resolves to this box and ports 80/443 are open."
if [[ -z "$BINARIES_RELEASE" ]]; then
  echo ""
  echo "  NEXT — get the (unsigned) Windows installers onto this box so 'Download"
  echo "  Installer' works. Easiest (no PC->VPS copy): publish them once with the"
  echo "  'Build unsigned installers' GitHub Action, then:"
  echo "     ./deploy/stage-binaries.sh --release unsigned-latest"
  echo "  Or from a local folder: ./deploy/stage-binaries.sh /path/to/installers"
fi
echo "============================================================================"
