// Command breeze-agent is the privileged RMM agent. It is a thin wrapper around
// internal/agentapp; the real program lives there so the GUI-subsystem
// breeze-user-helper sibling can build the identical code with a different
// embedded manifest. This binary embeds the requireAdministrator manifest
// (cmd/breeze-agent/rsrc_windows_amd64.syso, generated by `make build-winres`).
package main

import "github.com/breeze-rmm/agent/internal/agentapp"

// version is overridden at build time via -ldflags "-X main.version=...".
var version = "0.5.0"

func main() {
	agentapp.Main(version)
}
